# Generated by Django 5.2.14 on 2026-06-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
